[package]
name = "image_affinity"
version = "1.0.0"
authors = ["Daniel Busaba"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
argparse="*"
csv = "*"
rand = "*"
